Hetzner support functioning

diff --git a/sspaghetty b/sspaghetty
--- a/sspaghetty
+++ b/sspaghetty
@@ -74,7 +74,6 @@ hetzner_create_context() {
     spawn hcloud context create "Constellation"
     expect {
       "The HCLOUD_TOKEN environment variable is set. Do you want to use the token from HCLOUD_TOKEN for the new context? (Y/n): " { send "Y\r" }
-      "Are you sure you want to continue connecting (yes/no/[fingerprint])? " { send "yes\r" }
       timeout { exit 1 }
     }
     expect eof
@@ -474,13 +473,23 @@ connect() {
 	node_values
 	SSH_PASSWD=$(escape_string "$SSH_PASSWD")
 	echo -ne "${C_GREY_CENSOR1}${C_GREY_CENSOR2}"
-	if ! expect -c "spawn ssh -i ${NODE_SSH_ID} ${DROPLET_USER}@${NODE_IP} -p ${NODE_SSH_PORT};expect \"Enter passphrase\";send \"${SSH_PASSWD}\r\";interact"; then
-		echo -e "${C_INDIANRED1}> ${F_UNDERLINED}SSH CONNECTION FAILED"
-		error_exit
-	fi
+	expect << EOF
+    set timeout 10
+    spawn ssh -i ${NODE_SSH_ID} ${DROPLET_USER}@${NODE_IP} -p ${NODE_SSH_PORT}
+    expect {
+      "Enter passphrase" { send "${SSH_PASSWD}\r" }
+      "Are you sure you want to continue connecting " { send "yes\r" }
+      timeout { exit 1 }
+    }
+    expect eof
+EOF
+	# if ! expect -c "spawn ssh -i ${NODE_SSH_ID} ${DROPLET_USER}@${NODE_IP} -p ${NODE_SSH_PORT};expect {\"Enter passphrase\" { send \"${SSH_PASSWD}\r\";interact};\"Are you sure you want to continue connecting (yes/no/[fingerprint])? \" { send \"yes\r\";interact}}"; then
+	# 	echo -ne "${C_INDIANRED1}> ${F_UNDERLINED}SSH CONNECTION FAILED"
+	# 	error_exit
+	# fi
 }
 
-echo -e "${C_DEEPSKYBLUE3}${F_BOLD}"
+echo -ne "${C_DEEPSKYBLUE3}${F_BOLD}"
 cat <<EOF
   #################################
   #  SSPAGHETTY  NODE  CONNECTOR  #
@@ -495,7 +504,7 @@ example_process() {
     sleep 10 # Simulate a process running for 10 seconds
 }
 
-echo -e "${NO_FORMAT}"
+echo -ne "${NO_FORMAT}"
 case "${1}" in
 "uninstall") uninstall "${2}";;
 "install")
